require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DengonkaitousController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dengonkaitou. As you add validations to Dengonkaitou, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DengonkaitousController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dengonkaitous as @dengonkaitous" do
      dengonkaitou = Dengonkaitou.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dengonkaitous)).to eq([dengonkaitou])
    end
  end

  describe "GET #show" do
    it "assigns the requested dengonkaitou as @dengonkaitou" do
      dengonkaitou = Dengonkaitou.create! valid_attributes
      get :show, {:id => dengonkaitou.to_param}, valid_session
      expect(assigns(:dengonkaitou)).to eq(dengonkaitou)
    end
  end

  describe "GET #new" do
    it "assigns a new dengonkaitou as @dengonkaitou" do
      get :new, {}, valid_session
      expect(assigns(:dengonkaitou)).to be_a_new(Dengonkaitou)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dengonkaitou as @dengonkaitou" do
      dengonkaitou = Dengonkaitou.create! valid_attributes
      get :edit, {:id => dengonkaitou.to_param}, valid_session
      expect(assigns(:dengonkaitou)).to eq(dengonkaitou)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Dengonkaitou" do
        expect {
          post :create, {:dengonkaitou => valid_attributes}, valid_session
        }.to change(Dengonkaitou, :count).by(1)
      end

      it "assigns a newly created dengonkaitou as @dengonkaitou" do
        post :create, {:dengonkaitou => valid_attributes}, valid_session
        expect(assigns(:dengonkaitou)).to be_a(Dengonkaitou)
        expect(assigns(:dengonkaitou)).to be_persisted
      end

      it "redirects to the created dengonkaitou" do
        post :create, {:dengonkaitou => valid_attributes}, valid_session
        expect(response).to redirect_to(Dengonkaitou.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dengonkaitou as @dengonkaitou" do
        post :create, {:dengonkaitou => invalid_attributes}, valid_session
        expect(assigns(:dengonkaitou)).to be_a_new(Dengonkaitou)
      end

      it "re-renders the 'new' template" do
        post :create, {:dengonkaitou => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dengonkaitou" do
        dengonkaitou = Dengonkaitou.create! valid_attributes
        put :update, {:id => dengonkaitou.to_param, :dengonkaitou => new_attributes}, valid_session
        dengonkaitou.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dengonkaitou as @dengonkaitou" do
        dengonkaitou = Dengonkaitou.create! valid_attributes
        put :update, {:id => dengonkaitou.to_param, :dengonkaitou => valid_attributes}, valid_session
        expect(assigns(:dengonkaitou)).to eq(dengonkaitou)
      end

      it "redirects to the dengonkaitou" do
        dengonkaitou = Dengonkaitou.create! valid_attributes
        put :update, {:id => dengonkaitou.to_param, :dengonkaitou => valid_attributes}, valid_session
        expect(response).to redirect_to(dengonkaitou)
      end
    end

    context "with invalid params" do
      it "assigns the dengonkaitou as @dengonkaitou" do
        dengonkaitou = Dengonkaitou.create! valid_attributes
        put :update, {:id => dengonkaitou.to_param, :dengonkaitou => invalid_attributes}, valid_session
        expect(assigns(:dengonkaitou)).to eq(dengonkaitou)
      end

      it "re-renders the 'edit' template" do
        dengonkaitou = Dengonkaitou.create! valid_attributes
        put :update, {:id => dengonkaitou.to_param, :dengonkaitou => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dengonkaitou" do
      dengonkaitou = Dengonkaitou.create! valid_attributes
      expect {
        delete :destroy, {:id => dengonkaitou.to_param}, valid_session
      }.to change(Dengonkaitou, :count).by(-1)
    end

    it "redirects to the dengonkaitous list" do
      dengonkaitou = Dengonkaitou.create! valid_attributes
      delete :destroy, {:id => dengonkaitou.to_param}, valid_session
      expect(response).to redirect_to(dengonkaitous_url)
    end
  end

end
