require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EkisController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Eki. As you add validations to Eki, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EkisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ekis as @ekis" do
      eki = Eki.create! valid_attributes
      get :index_old, {}, valid_session
      expect(assigns(:ekis)).to eq([eki])
    end
  end

  describe "GET #show" do
    it "assigns the requested eki as @eki" do
      eki = Eki.create! valid_attributes
      get :show, {:id => eki.to_param}, valid_session
      expect(assigns(:eki)).to eq(eki)
    end
  end

  describe "GET #new" do
    it "assigns a new eki as @eki" do
      get :new, {}, valid_session
      expect(assigns(:eki)).to be_a_new(Eki)
    end
  end

  describe "GET #edit" do
    it "assigns the requested eki as @eki" do
      eki = Eki.create! valid_attributes
      get :edit, {:id => eki.to_param}, valid_session
      expect(assigns(:eki)).to eq(eki)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Eki" do
        expect {
          post :create, {:eki => valid_attributes}, valid_session
        }.to change(Eki, :count).by(1)
      end

      it "assigns a newly created eki as @eki" do
        post :create, {:eki => valid_attributes}, valid_session
        expect(assigns(:eki)).to be_a(Eki)
        expect(assigns(:eki)).to be_persisted
      end

      it "redirects to the created eki" do
        post :create, {:eki => valid_attributes}, valid_session
        expect(response).to redirect_to(Eki.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved eki as @eki" do
        post :create, {:eki => invalid_attributes}, valid_session
        expect(assigns(:eki)).to be_a_new(Eki)
      end

      it "re-renders the 'new' template" do
        post :create, {:eki => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested eki" do
        eki = Eki.create! valid_attributes
        put :update, {:id => eki.to_param, :eki => new_attributes}, valid_session
        eki.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested eki as @eki" do
        eki = Eki.create! valid_attributes
        put :update, {:id => eki.to_param, :eki => valid_attributes}, valid_session
        expect(assigns(:eki)).to eq(eki)
      end

      it "redirects to the eki" do
        eki = Eki.create! valid_attributes
        put :update, {:id => eki.to_param, :eki => valid_attributes}, valid_session
        expect(response).to redirect_to(eki)
      end
    end

    context "with invalid params" do
      it "assigns the eki as @eki" do
        eki = Eki.create! valid_attributes
        put :update, {:id => eki.to_param, :eki => invalid_attributes}, valid_session
        expect(assigns(:eki)).to eq(eki)
      end

      it "re-renders the 'edit' template" do
        eki = Eki.create! valid_attributes
        put :update, {:id => eki.to_param, :eki => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested eki" do
      eki = Eki.create! valid_attributes
      expect {
        delete :destroy, {:id => eki.to_param}, valid_session
      }.to change(Eki, :count).by(-1)
    end

    it "redirects to the ekis list" do
      eki = Eki.create! valid_attributes
      delete :destroy, {:id => eki.to_param}, valid_session
      expect(response).to redirect_to(ekis_url)
    end
  end

end
