require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ShozaisController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Shozai. As you add validations to Shozai, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShozaisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all shozais as @shozais" do
      shozai = Shozai.create! valid_attributes
      get :index_old, {}, valid_session
      expect(assigns(:shozais)).to eq([shozai])
    end
  end

  describe "GET #show" do
    it "assigns the requested shozai as @shozai" do
      shozai = Shozai.create! valid_attributes
      get :show, {:id => shozai.to_param}, valid_session
      expect(assigns(:shozai)).to eq(shozai)
    end
  end

  describe "GET #new" do
    it "assigns a new shozai as @shozai" do
      get :new, {}, valid_session
      expect(assigns(:shozai)).to be_a_new(Shozai)
    end
  end

  describe "GET #edit" do
    it "assigns the requested shozai as @shozai" do
      shozai = Shozai.create! valid_attributes
      get :edit, {:id => shozai.to_param}, valid_session
      expect(assigns(:shozai)).to eq(shozai)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Shozai" do
        expect {
          post :create, {:shozai => valid_attributes}, valid_session
        }.to change(Shozai, :count).by(1)
      end

      it "assigns a newly created shozai as @shozai" do
        post :create, {:shozai => valid_attributes}, valid_session
        expect(assigns(:shozai)).to be_a(Shozai)
        expect(assigns(:shozai)).to be_persisted
      end

      it "redirects to the created shozai" do
        post :create, {:shozai => valid_attributes}, valid_session
        expect(response).to redirect_to(Shozai.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved shozai as @shozai" do
        post :create, {:shozai => invalid_attributes}, valid_session
        expect(assigns(:shozai)).to be_a_new(Shozai)
      end

      it "re-renders the 'new' template" do
        post :create, {:shozai => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shozai" do
        shozai = Shozai.create! valid_attributes
        put :update, {:id => shozai.to_param, :shozai => new_attributes}, valid_session
        shozai.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested shozai as @shozai" do
        shozai = Shozai.create! valid_attributes
        put :update, {:id => shozai.to_param, :shozai => valid_attributes}, valid_session
        expect(assigns(:shozai)).to eq(shozai)
      end

      it "redirects to the shozai" do
        shozai = Shozai.create! valid_attributes
        put :update, {:id => shozai.to_param, :shozai => valid_attributes}, valid_session
        expect(response).to redirect_to(shozai)
      end
    end

    context "with invalid params" do
      it "assigns the shozai as @shozai" do
        shozai = Shozai.create! valid_attributes
        put :update, {:id => shozai.to_param, :shozai => invalid_attributes}, valid_session
        expect(assigns(:shozai)).to eq(shozai)
      end

      it "re-renders the 'edit' template" do
        shozai = Shozai.create! valid_attributes
        put :update, {:id => shozai.to_param, :shozai => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested shozai" do
      shozai = Shozai.create! valid_attributes
      expect {
        delete :destroy, {:id => shozai.to_param}, valid_session
      }.to change(Shozai, :count).by(-1)
    end

    it "redirects to the shozais list" do
      shozai = Shozai.create! valid_attributes
      delete :destroy, {:id => shozai.to_param}, valid_session
      expect(response).to redirect_to(shozais_url)
    end
  end

end
