require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TsushinseigyousController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tsushinseigyou. As you add validations to Tsushinseigyou, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TsushinseigyousController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all tsushinseigyous as @tsushinseigyous" do
      tsushinseigyou = Tsushinseigyou.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tsushinseigyous)).to eq([tsushinseigyou])
    end
  end

  describe "GET #show" do
    it "assigns the requested tsushinseigyou as @tsushinseigyou" do
      tsushinseigyou = Tsushinseigyou.create! valid_attributes
      get :show, {:id => tsushinseigyou.to_param}, valid_session
      expect(assigns(:tsushinseigyou)).to eq(tsushinseigyou)
    end
  end

  describe "GET #new" do
    it "assigns a new tsushinseigyou as @tsushinseigyou" do
      get :new, {}, valid_session
      expect(assigns(:tsushinseigyou)).to be_a_new(Tsushinseigyou)
    end
  end

  describe "GET #edit" do
    it "assigns the requested tsushinseigyou as @tsushinseigyou" do
      tsushinseigyou = Tsushinseigyou.create! valid_attributes
      get :edit, {:id => tsushinseigyou.to_param}, valid_session
      expect(assigns(:tsushinseigyou)).to eq(tsushinseigyou)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Tsushinseigyou" do
        expect {
          post :create, {:tsushinseigyou => valid_attributes}, valid_session
        }.to change(Tsushinseigyou, :count).by(1)
      end

      it "assigns a newly created tsushinseigyou as @tsushinseigyou" do
        post :create, {:tsushinseigyou => valid_attributes}, valid_session
        expect(assigns(:tsushinseigyou)).to be_a(Tsushinseigyou)
        expect(assigns(:tsushinseigyou)).to be_persisted
      end

      it "redirects to the created tsushinseigyou" do
        post :create, {:tsushinseigyou => valid_attributes}, valid_session
        expect(response).to redirect_to(Tsushinseigyou.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved tsushinseigyou as @tsushinseigyou" do
        post :create, {:tsushinseigyou => invalid_attributes}, valid_session
        expect(assigns(:tsushinseigyou)).to be_a_new(Tsushinseigyou)
      end

      it "re-renders the 'new' template" do
        post :create, {:tsushinseigyou => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tsushinseigyou" do
        tsushinseigyou = Tsushinseigyou.create! valid_attributes
        put :update, {:id => tsushinseigyou.to_param, :tsushinseigyou => new_attributes}, valid_session
        tsushinseigyou.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tsushinseigyou as @tsushinseigyou" do
        tsushinseigyou = Tsushinseigyou.create! valid_attributes
        put :update, {:id => tsushinseigyou.to_param, :tsushinseigyou => valid_attributes}, valid_session
        expect(assigns(:tsushinseigyou)).to eq(tsushinseigyou)
      end

      it "redirects to the tsushinseigyou" do
        tsushinseigyou = Tsushinseigyou.create! valid_attributes
        put :update, {:id => tsushinseigyou.to_param, :tsushinseigyou => valid_attributes}, valid_session
        expect(response).to redirect_to(tsushinseigyou)
      end
    end

    context "with invalid params" do
      it "assigns the tsushinseigyou as @tsushinseigyou" do
        tsushinseigyou = Tsushinseigyou.create! valid_attributes
        put :update, {:id => tsushinseigyou.to_param, :tsushinseigyou => invalid_attributes}, valid_session
        expect(assigns(:tsushinseigyou)).to eq(tsushinseigyou)
      end

      it "re-renders the 'edit' template" do
        tsushinseigyou = Tsushinseigyou.create! valid_attributes
        put :update, {:id => tsushinseigyou.to_param, :tsushinseigyou => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested tsushinseigyou" do
      tsushinseigyou = Tsushinseigyou.create! valid_attributes
      expect {
        delete :destroy, {:id => tsushinseigyou.to_param}, valid_session
      }.to change(Tsushinseigyou, :count).by(-1)
    end

    it "redirects to the tsushinseigyous list" do
      tsushinseigyou = Tsushinseigyou.create! valid_attributes
      delete :destroy, {:id => tsushinseigyou.to_param}, valid_session
      expect(response).to redirect_to(tsushinseigyous_url)
    end
  end

end
